name: componentt
description: A library to simplify working with the intents, actions, and state of a component
version: 0.5.0
repository: https://github.com/bysensa/componentt

environment:
  sdk: '>=2.13.0 <4.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

