name: componentt
description: A library for creating fully functional visual components.
version: 0.1.0
repository: https://github.com/bysensa/componentt

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

